const colors = [
  { fileName: 'primary_Black1.png', hex: '#5a5a5a', name: 'Black 1' },
  { fileName: 'secondary_Black1.png', hex: '#5a5a5a', name: 'Black 1' },
  { fileName: 'primary_Black2.png', hex: '#424242', name: 'Black 2' },
  { fileName: 'secondary_Black2.png', hex: '#424242', name: 'Black 2' },
  { fileName: 'primary_Black3.png', hex: '#303030', name: 'Black 3' },
  { fileName: 'secondary_Black3.png', hex: '#303030', name: 'Black 3' },
  { fileName: 'primary_Blue1.png', hex: '#42579e', name: 'Blue 1' },
  { fileName: 'secondary_Blue1.png', hex: '#42579e', name: 'Blue 1' },
  { fileName: 'primary_Blue2.png', hex: '#303f75', name: 'Blue 2' },
  { fileName: 'secondary_Blue2.png', hex: '#303f75', name: 'Blue 2' },
  { fileName: 'primary_Blue3.png', hex: '#232e55', name: 'Blue 3' },
  { fileName: 'secondary_Blue3.png', hex: '#232e55', name: 'Blue 3' },
  { fileName: 'primary_Bone1.png', hex: '#f5f4e1', name: 'Bone 1' },
  { fileName: 'secondary_Bone1.png', hex: '#f5f4e1', name: 'Bone 1' },
  { fileName: 'primary_Bone2.png', hex: '#e7e8d6', name: 'Bone 2' },
  { fileName: 'secondary_Bone2.png', hex: '#e7e8d6', name: 'Bone 2' },
  { fileName: 'primary_Bone3.png', hex: '#d4d7b1', name: 'Bone 3' },
  { fileName: 'secondary_Bone3.png', hex: '#d4d7b1', name: 'Bone 3' },
  { fileName: 'primary_Brown1.png', hex: '#73701f', name: 'Brown 1' },
  { fileName: 'secondary_Brown1.png', hex: '#73701f', name: 'Brown 1' },
  { fileName: 'primary_Brown2.png', hex: '#56541e', name: 'Brown 2' },
  { fileName: 'secondary_Brown2.png', hex: '#56541e', name: 'Brown 2' },
  { fileName: 'primary_Brown3.png', hex: '#373613', name: 'Brown 3' },
  { fileName: 'secondary_Brown3.png', hex: '#373613', name: 'Brown 3' },
  { fileName: 'primary_Copper1.png', hex: '#885829', name: 'Copper 1' },
  { fileName: 'secondary_Copper1.png', hex: '#885829', name: 'Copper 1' },
  { fileName: 'primary_Copper2.png', hex: '#885829', name: 'Copper 2' },
  { fileName: 'secondary_Copper2.png', hex: '#885829', name: 'Copper 2' },
  { fileName: 'primary_Copper3.png', hex: '#885829', name: 'Copper 3' },
  { fileName: 'secondary_Copper3.png', hex: '#885829', name: 'Copper 3' },
  { fileName: 'primary_Crimson1.png', hex: '#903232', name: 'Crimson 1' },
  { fileName: 'secondary_Crimson1.png', hex: '#903232', name: 'Crimson 1' },
  { fileName: 'primary_Crimson2.png', hex: '#7b1d1d', name: 'Crimson 2' },
  { fileName: 'secondary_Crimson2.png', hex: '#7b1d1d', name: 'Crimson 2' },
  { fileName: 'primary_Crimson3.png', hex: '#631414', name: 'Crimson 3' },
  { fileName: 'secondary_Crimson3.png', hex: '#631414', name: 'Crimson 3' },
  { fileName: 'primary_Eggshell1.png', hex: '#f8f0ea', name: 'Eggshell 1' },
  { fileName: 'secondary_Eggshell1.png', hex: '#f8f0ea', name: 'Eggshell 1' },
  { fileName: 'primary_Eggshell2.png', hex: '#eee0d7', name: 'Eggshell 2' },
  { fileName: 'secondary_Eggshell2.png', hex: '#eee0d7', name: 'Eggshell 2' },
  { fileName: 'primary_Eggshell3.png', hex: '#dbc7bc', name: 'Eggshell 3' },
  { fileName: 'secondary_Eggshell3.png', hex: '#dbc7bc', name: 'Eggshell 3' },
  { fileName: 'primary_Flame1.png', hex: '#ff9e2c', name: 'Flame 1' },
  { fileName: 'secondary_Flame1.png', hex: '#ff9e2c', name: 'Flame 1' },
  { fileName: 'primary_Flame2.png', hex: '#ff7706', name: 'Flame 2' },
  { fileName: 'secondary_Flame2.png', hex: '#ff7706', name: 'Flame 2' },
  { fileName: 'primary_Flame3.png', hex: '#b95000', name: 'Flame 3' },
  { fileName: 'secondary_Flame3.png', hex: '#b95000', name: 'Flame 3' },
  { fileName: 'primary_Gold1.png', hex: '#ffec7f', name: 'Gold 1' },
  { fileName: 'secondary_Gold1.png', hex: '#ffec7f', name: 'Gold 1' },
  { fileName: 'primary_Gold2.png', hex: '#ecd451', name: 'Gold 2' },
  { fileName: 'secondary_Gold2.png', hex: '#ecd451', name: 'Gold 2' },
  { fileName: 'primary_Gold3.png', hex: '#bba323', name: 'Gold 3' },
  { fileName: 'secondary_Gold3.png', hex: '#bba323', name: 'Gold 3' },
  { fileName: 'primary_Green1.png', hex: '#1b8546', name: 'Green 1' },
  { fileName: 'secondary_Green1.png', hex: '#1b8546', name: 'Green 1' },
  { fileName: 'primary_Green2.png', hex: '#2d9055', name: 'Green 2' },
  { fileName: 'secondary_Green2.png', hex: '#2d9055', name: 'Green 2' },
  { fileName: 'primary_Green3.png', hex: '#216a3e', name: 'Green 3' },
  { fileName: 'secondary_Green3.png', hex: '#216a3e', name: 'Green 3' },
  { fileName: 'primary_Lilac1.png', hex: '#c8a2c8', name: 'Lilac 1' },
  { fileName: 'secondary_Lilac1.png', hex: '#c8a2c8', name: 'Lilac 1' },
  { fileName: 'primary_Lilac2.png', hex: '#aa86aa', name: 'Lilac 2' },
  { fileName: 'secondary_Lilac2.png', hex: '#aa86aa', name: 'Lilac 2' },
  { fileName: 'primary_Lilac3.png', hex: '#8d6e8d', name: 'Lilac 3' },
  { fileName: 'secondary_Lilac3.png', hex: '#8d6e8d', name: 'Lilac 3' },
  { fileName: 'primary_Lincoln1.png', hex: '#2a6b16', name: 'Lincoln 1' },
  { fileName: 'secondary_Lincoln1.png', hex: '#2a6b16', name: 'Lincoln 1' },
  { fileName: 'primary_Lincoln2.png', hex: '#225612', name: 'Lincoln 2' },
  { fileName: 'secondary_Lincoln2.png', hex: '#225612', name: 'Lincoln 2' },
  { fileName: 'primary_Lincoln3.png', hex: '#19400d', name: 'Lincoln 3' },
  { fileName: 'secondary_Lincoln3.png', hex: '#19400d', name: 'Lincoln 3' },
  { fileName: 'primary_Maroon1.png', hex: '#8d3e3e', name: 'Maroon 1' },
  { fileName: 'secondary_Maroon1.png', hex: '#8d3e3e', name: 'Maroon 1' },
  { fileName: 'primary_Maroon2.png', hex: '#722e2e', name: 'Maroon 2' },
  { fileName: 'secondary_Maroon2.png', hex: '#722e2e', name: 'Maroon 2' },
  { fileName: 'primary_Maroon3.png', hex: '#5b2121', name: 'Maroon 3' },
  { fileName: 'secondary_Maroon3.png', hex: '#5b2121', name: 'Maroon 3' },
  { fileName: 'primary_Mint1.png', hex: '#acb8a9', name: 'Mint 1' },
  { fileName: 'secondary_Mint1.png', hex: '#acb8a9', name: 'Mint 1' },
  { fileName: 'primary_Mint2.png', hex: '#8f9a8c', name: 'Mint 2' },
  { fileName: 'secondary_Mint2.png', hex: '#8f9a8c', name: 'Mint 2' },
  { fileName: 'primary_Mint3.png', hex: '#6d776a', name: 'Mint 3' },
  { fileName: 'secondary_Mint3.png', hex: '#6d776a', name: 'Mint 3' },
  { fileName: 'primary_Night1.png', hex: '#435570', name: 'Night 1' },
  { fileName: 'secondary_Night1.png', hex: '#435570', name: 'Night 1' },
  { fileName: 'primary_Night2.png', hex: '#37465c', name: 'Night 2' },
  { fileName: 'secondary_Night2.png', hex: '#37465c', name: 'Night 2' },
  { fileName: 'primary_Night3.png', hex: '#2e3b4d', name: 'Night 3' },
  { fileName: 'secondary_Night3.png', hex: '#2e3b4d', name: 'Night 3' },
  { fileName: 'primary_Pink1.png', hex: '#e2b1ba', name: 'Pink 1' },
  { fileName: 'secondary_Pink1.png', hex: '#e2b1ba', name: 'Pink 1' },
  { fileName: 'primary_Pink2.png', hex: '#d69ba6', name: 'Pink 2' },
  { fileName: 'secondary_Pink2.png', hex: '#d69ba6', name: 'Pink 2' },
  { fileName: 'primary_Pink3.png', hex: '#bb7b86', name: 'Pink 3' },
  { fileName: 'secondary_Pink3.png', hex: '#bb7b86', name: 'Pink 3' },
  { fileName: 'primary_Purple1.png', hex: '#8a3ea0', name: 'Purple 1' },
  { fileName: 'secondary_Purple1.png', hex: '#8a3ea0', name: 'Purple 1' },
  { fileName: 'primary_Purple2.png', hex: '#692f7b', name: 'Purple 2' },
  { fileName: 'secondary_Purple2.png', hex: '#692f7b', name: 'Purple 2' },
  { fileName: 'primary_Purple3.png', hex: '#50245d', name: 'Purple 3' },
  { fileName: 'secondary_Purple3.png', hex: '#50245d', name: 'Purple 3' },
  { fileName: 'primary_Red1.png', hex: '#b52c37', name: 'Red 1' },
  { fileName: 'secondary_Red1.png', hex: '#b52c37', name: 'Red 1' },
  { fileName: 'primary_Red2.png', hex: '#981e28', name: 'Red 2' },
  { fileName: 'secondary_Red2.png', hex: '#981e28', name: 'Red 2' },
  { fileName: 'primary_Red3.png', hex: '#82151e', name: 'Red 3' },
  { fileName: 'secondary_Red3.png', hex: '#82151e', name: 'Red 3' },
  { fileName: 'primary_Sea1.png', hex: '#a7d1ed', name: 'Sea 1' },
  { fileName: 'secondary_Sea1.png', hex: '#a7d1ed', name: 'Sea 1' },
  { fileName: 'primary_Sea2.png', hex: '#8bb4d8', name: 'Sea 2' },
  { fileName: 'secondary_Sea2.png', hex: '#8bb4d8', name: 'Sea 2' },
  { fileName: 'primary_Sea3.png', hex: '#7498be', name: 'Sea 3' },
  { fileName: 'secondary_Sea3.png', hex: '#7498be', name: 'Sea 3' },
  { fileName: 'primary_Silver1.png', hex: '#daedec', name: 'Silver 1' },
  { fileName: 'secondary_Silver1.png', hex: '#daedec', name: 'Silver 1' },
  { fileName: 'primary_Silver2.png', hex: '#afc3c1', name: 'Silver 2' },
  { fileName: 'secondary_Silver2.png', hex: '#afc3c1', name: 'Silver 2' },
  { fileName: 'primary_Silver3.png', hex: '#9cb5b2', name: 'Silver 3' },
  { fileName: 'secondary_Silver3.png', hex: '#9cb5b2', name: 'Silver 3' },
  { fileName: 'primary_Sky1.png', hex: '#84d1ff', name: 'Sky 1' },
  { fileName: 'secondary_Sky1.png', hex: '#84d1ff', name: 'Sky 1' },
  { fileName: 'primary_Sky2.png', hex: '#6eb6ff', name: 'Sky 2' },
  { fileName: 'secondary_Sky2.png', hex: '#6eb6ff', name: 'Sky 2' },
  { fileName: 'primary_Sky3.png', hex: '#2675e5', name: 'Sky 3' },
  { fileName: 'secondary_Sky3.png', hex: '#2675e5', name: 'Sky 3' },
  { fileName: 'primary_Stone1.png', hex: '#878787', name: 'Stone 1' },
  { fileName: 'secondary_Stone1.png', hex: '#878787', name: 'Stone 1' },
  { fileName: 'primary_Stone2.png', hex: '#686868', name: 'Stone 2' },
  { fileName: 'secondary_Stone2.png', hex: '#686868', name: 'Stone 2' },
  { fileName: 'primary_Stone3.png', hex: '#5f5f5f', name: 'Stone 3' },
  { fileName: 'secondary_Stone3.png', hex: '#5f5f5f', name: 'Stone 3' },
  { fileName: 'primary_Tan1.png', hex: '#b2ab99', name: 'Tan 1' },
  { fileName: 'secondary_Tan1.png', hex: '#b2ab99', name: 'Tan 1' },
  { fileName: 'primary_Tan2.png', hex: '#afa795', name: 'Tan 2' },
  { fileName: 'secondary_Tan2.png', hex: '#afa795', name: 'Tan 2' },
  { fileName: 'primary_Tan3.png', hex: '#968f7f', name: 'Tan 3' },
  { fileName: 'secondary_Tan3.png', hex: '#968f7f', name: 'Tan 3' },
  { fileName: 'primary_Vermilion1.png', hex: '#a38e3c', name: 'Vermilion 1' },
  { fileName: 'secondary_Vermilion1.png', hex: '#a38e3c', name: 'Vermilion 1' },
  { fileName: 'primary_Vermilion2.png', hex: '#6b5b19', name: 'Vermilion 2' },
  { fileName: 'secondary_Vermilion2.png', hex: '#6b5b19', name: 'Vermilion 2' },
  { fileName: 'primary_Vermilion3.png', hex: '#5c4e15', name: 'Vermilion 3' },
  { fileName: 'secondary_Vermilion3.png', hex: '#5c4e15', name: 'Vermilion 3' },
  { fileName: 'primary_White1.png', hex: '#ffffff', name: 'White 1' },
  { fileName: 'secondary_White1.png', hex: '#ffffff', name: 'White 1' },
  { fileName: 'primary_White2.png', hex: '#e5dbe2', name: 'White 2' },
  { fileName: 'secondary_White2.png', hex: '#e5dbe2', name: 'White 2' },
  { fileName: 'primary_White3.png', hex: '#e6dbe0', name: 'White 3' },
  { fileName: 'secondary_White3.png', hex: '#e6dbe0', name: 'White 3' },
  { fileName: 'primary_Wood1.png', hex: '#c19a6b', name: 'Wood 1' },
  { fileName: 'secondary_Wood1.png', hex: '#c19a6b', name: 'Wood 1' },
  { fileName: 'primary_Wood2.png', hex: '#9e7a54', name: 'Wood 2' },
  { fileName: 'secondary_Wood2.png', hex: '#9e7a54', name: 'Wood 2' },
  { fileName: 'primary_Wood3.png', hex: '#836445', name: 'Wood 3' },
  { fileName: 'secondary_Wood3.png', hex: '#836445', name: 'Wood 3' },
  { fileName: 'primary_Yellow1.png', hex: '#fbf8bf', name: 'Yellow 1' },
  { fileName: 'secondary_Yellow1.png', hex: '#fbf8bf', name: 'Yellow 1' },
  { fileName: 'primary_Yellow2.png', hex: '#f5f882', name: 'Yellow 2' },
  { fileName: 'secondary_Yellow2.png', hex: '#f5f882', name: 'Yellow 2' },
  { fileName: 'primary_Yellow3.png', hex: '#d5da60', name: 'Yellow 3' },
  { fileName: 'secondary_Yellow3.png', hex: '#d5da60', name: 'Yellow 3' },
  { fileName: 'primary_None.png', hex: '', name: 'Empty' },
  { fileName: 'secondary_None.png', hex: '', name: 'Empty' },
  // skin
  { name: 'Beige', hex: '#e5b770', fileName: 'primary_Beige.png' },
  { name: 'Beige', hex: '#e5b770', fileName: 'secondary_Beige.png' },
  { name: 'Brick', hex: '#8f6e4d', fileName: 'primary_Brick.png' },
  { name: 'Brick', hex: '#8f6e4d', fileName: 'secondary_Brick.png' },
  { name: 'Bronze', hex: '#ce955c', fileName: 'primary_Bronze.png' },
  { name: 'Bronze', hex: '#ce955c', fileName: 'secondary_Bronze.png' },
  { name: 'Caucasian', hex: '#e6c8aa', fileName: 'primary_Caucasian.png' },
  { name: 'Caucasian', hex: '#e6c8aa', fileName: 'secondary_Caucasian.png' },
  { name: 'Celestial', hex: '#98b0d8', fileName: 'primary_Celestial.png' },
  { name: 'Celestial', hex: '#98b0d8', fileName: 'secondary_Celestial.png' },
  { name: 'Chestnut', hex: '#754a27', fileName: 'primary_Chestnut.png' },
  { name: 'Chestnut', hex: '#754a27', fileName: 'secondary_Chestnut.png' },
  { name: 'Chocolate', hex: '#4c2a1e', fileName: 'primary_Chocolate.png' },
  { name: 'Chocolate', hex: '#4c2a1e', fileName: 'secondary_Chocolate.png' },
  { name: 'Cinder', hex: '#343434', fileName: 'primary_Cinder.png' },
  { name: 'Cinder', hex: '#343434', fileName: 'secondary_Cinder.png' },
  { name: 'Dust', hex: '#706e54', fileName: 'primary_Dust.png' },
  { name: 'Dust', hex: '#706e54', fileName: 'secondary_Dust.png' },
  { name: 'Grey', hex: '#7b7b7b', fileName: 'primary_Grey.png' },
  { name: 'Grey', hex: '#7b7b7b', fileName: 'secondary_Grey.png' },
  { name: 'Honey', hex: '#a38836', fileName: 'primary_Honey.png' },
  { name: 'Honey', hex: '#a38836', fileName: 'secondary_Honey.png' },
  { name: 'Jade', hex: '#2e9b5b', fileName: 'primary_Jade.png' },
  { name: 'Jade', hex: '#2e9b5b', fileName: 'secondary_Jade.png' },
  { name: 'Lavender', hex: '#81478e', fileName: 'primary_Lavender.png' },
  { name: 'Lavender', hex: '#81478e', fileName: 'secondary_Lavender.png' },
  { name: 'Olive', hex: '#967644', fileName: 'primary_Olive.png' },
  { name: 'Olive', hex: '#967644', fileName: 'secondary_Olive.png' },
  { name: 'Pale', hex: '#f3d6ba', fileName: 'primary_Pale.png' },
  { name: 'Pale', hex: '#f3d6ba', fileName: 'secondary_Pale.png' },
  { name: 'Porcelain', hex: '#f4eef2', fileName: 'primary_Porcelain.png' },
  { name: 'Porcelain', hex: '#f4eef2', fileName: 'secondary_Porcelain.png' },
  { name: 'Sanguine', hex: '#9a2424', fileName: 'primary_Sanguine.png' },
  { name: 'Sanguine', hex: '#9a2424', fileName: 'secondary_Sanguine.png' },
  { name: 'Skeleton', hex: '#d4d7b1', fileName: 'primary_Skeleton.png' },
  { name: 'Skeleton', hex: '#d4d7b1', fileName: 'secondary_Skeleton.png' },
  { name: 'Storm', hex: '#3b4c67', fileName: 'primary_Storm.png' },
  { name: 'Storm', hex: '#3b4c67', fileName: 'secondary_Storm.png' },
  { name: 'Sunbeam', hex: '#e4e96d', fileName: 'primary_Sunbeam.png' },
  { name: 'Sunbeam', hex: '#e4e96d', fileName: 'secondary_Sunbeam.png' },
  { name: 'Swarthy', hex: '#8f6527', fileName: 'primary_Swarthy.png' },
  { name: 'Swarthy', hex: '#8f6527', fileName: 'secondary_Swarthy.png' },
]

export default colors
