const colors = [
  {fileName: 'Black.png', hex: '#393939', name: 'Black'},
  {fileName: 'Blue.png', hex: '#334789', name: 'Blue'},
  {fileName: 'blue.png', hex: '#334789', name: 'blue'},
  {fileName: 'Brown.png', hex: '#594511', name: 'Brown'},
  {fileName: 'Copper.png', hex: '#885829', name: 'Copper'},
  {fileName: 'Crimson.png', hex: '#6d1818', name: 'Crimson'},
  {fileName: 'Eggshell.png', hex: '#f6eae0', name: 'Eggshell'},
  {fileName: 'Flame.png', hex: '#c47414', name: 'Flame'},
  {fileName: 'Gold.png', hex: '#ccb434', name: 'Gold'},
  {fileName: 'Green.png', hex: '#0c4c2c', name: 'Green'},
  {fileName: 'Maroon.png', hex: '#6d2626', name: 'Maroon'},
  {fileName: 'Mint.png', hex: '#869e80', name: 'Mint'},
  {fileName: 'Night.png', hex: '#27364d', name: 'Night'},
  {fileName: 'Pink.png', hex: '#bb8992', name: 'Pink'},
  {fileName: 'Purple.png', hex: '#421151', name: 'Purple'},
  {fileName: 'Red.png', hex: '#8a1821', name: 'Red'},
  {fileName: 'Sea.png', hex: '#507399', name: 'Sea'},
  {fileName: 'Silver.png', hex: '#afc0bf', name: 'Silver'},
  {fileName: 'Sky.png', hex: '#1280ec', name: 'Sky'},
  {fileName: 'Stone.png', hex: '#4e5254', name: 'Stone'},
  {fileName: 'Tan.png', hex: '#83785e', name: 'Tan'},
  {fileName: 'White.png', hex: '#f4eef2', name: 'White'},
  {fileName: 'Wood.png', hex: '#a07d53', name: 'Wood'},
  {fileName: 'Yellow.png', hex: '#dde655', name: 'Yellow'},
  {fileName: 'Bone.png', hex: '#d4d7b1', name: 'Bone'},
  {fileName: 'None.png', hex: '', name: 'Empty'},
  // skin
  
  { name: 'Brick', hex: '#8f6e4d', fileName: 'Brick.png' },
  { name: 'Bronze', hex: '#ce955c', fileName: 'Bronze.png' },
  { name: 'Caucasian', hex: '#e6c8aa', fileName: 'Caucasian.png' },
  { name: 'Chocolate', hex: '#4c2a1e', fileName: 'Chocolate.png' },
  { name: 'Dust', hex: '#706e54', fileName: 'Dust.png' },
  { name: 'Grey', hex: '#7b7b7b', fileName: 'Grey.png' },
  { name: 'Honey', hex: '#a38836', fileName: 'Honey.png' },
  { name: 'Olive', hex: '#967644', fileName: 'Olive.png' },
  { name: 'Pale', hex: '#f3d6ba', fileName: 'Pale.png' },
  { name: 'Porcelain', hex: '#f4eef2', fileName: 'Porcelain.png' },
  { name: 'Skeleton', hex: '#d4d7b1', fileName: 'Skeleton.png' },
  { name: 'Swarthy', hex: '#8f6527', fileName: 'Swarthy.png' },

]

export default colors