const newData = {
  Accessories: {
    Amulet: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Apron: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Ale_Belly: ['blue.png', 'bronze.png', 'brown.png', 'gold.png', 'green.png', 'grey.png', 'night.png', 'pale.png', 'purple.png', 'red.png', 'tan.png'],
    Arcane_Collar: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Bandana: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Blindfold: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Brawler_Gauntlets: ['black.png', 'blue.png', 'brown.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Breasts: ['blue.png', 'bronze.png', 'brown.png', 'gold.png', 'green.png', 'grey.png', 'night.png', 'pale.png', 'purple.png', 'red.png', 'tan.png'],
    Champion_Belt: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Circlet: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Cultist_Sash: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Cultist_Shawl: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Demon_Horns: ['black.png', 'gold.png', 'ivory.png', 'red.png', 'tan.png'],
    Dancer_Veil: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Devil_Horns: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Duelist_Cape: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Desert_Cloak: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Elite_Belt: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Epaulettes: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Falconer_Glove: [
      'left_black.png',
      'left_blue.png',
      'left_brown.png',
      'left_gold.png',
      'left_green.png',
      'left_ivory.png',
      'left_night.png',
      'left_red.png',
      'left_tan.png',
      'left_white.png',
      'right_black.png',
      'right_blue.png',
      'right_brown.png',
      'right_gold.png',
      'right_green.png',
      'right_ivory.png',
      'right_night.png',
      'right_red.png',
      'right_tan.png',
      'right_white.png',
    ],
    Fools_Garland: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Faun_Horns: ['black.png', 'brown.png', 'gold.png', 'ivory.png', 'night.png', 'red.png', 'white.png'],
    Imp_Horns: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Grim_Sash: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Lunar_Cape: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Leather_Cape: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Nemean_Pelt: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Pauldron: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Sash: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'red.png', 'tan.png', 'white.png'],
    Ram_Horns: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Shaman_Skull: ['Bleached.png', 'Bone.png', 'Chief_Bleached.png', 'Chief_Bone.png'],
    Sharp_Horns: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Silk_Scarf: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Skull: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Toth_s_Wing: ['brown.png', 'white.png'],
    Traveler_Cloak: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Thieves_Shawl: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Tatters: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Underworld_Horns: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Veil: [
      'black.png',
      'blue.png',
      'brown.png',
      'gold.png',
      'green.png',
      'ivory.png',
      'night.png',
      'red.png',
      'sheer_black.png',
      'sheer_blue.png',
      'sheer_brown.png',
      'sheer_gold.png',
      'sheer_green.png',
      'sheer_ivory.png',
      'sheer_night.png',
      'sheer_red.png',
      'sheer_tan.png',
      'sheer_white.png',
      'tan.png',
      'white.png',
    ],
    Winged_Crown: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Wreath: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
  },
  Face: {
    Angry_Brows: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Arcane_Beard: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Cyclops_Eye: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Determined_Brows: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Endless_Beard: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Eyepatch: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Face_Shadow: ['black.png'],
    Eye_Color: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Full_Beard: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Goatee: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Goggles: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Goddess_Eyeliner: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Hermit_Beard: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Knit_Brows: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Mage_Countenance: ['blue.png', 'gold.png', 'green.png', 'night.png', 'red.png', 'white.png'],
    Mask: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Monocle: ['black.png', 'blue.png', 'gold.png', 'green.png', 'red.png', 'white.png'],
    Mouth: ['a.png', 'b.png', 'c.png', 'd.png'],
    Mustache: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Ocular_Implant: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Pirate_Beard: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Pointed_Ear: ['blue.png', 'bronze.png', 'brown.png', 'gold.png', 'green.png', 'grey.png', 'night.png', 'pale.png', 'red.png', 'tan.png'],
    Politician_Chin: ['blue.png', 'bronze.png', 'brown.png', 'gold.png', 'green.png', 'grey.png', 'night.png', 'pale.png', 'purple.png', 'red.png', 'tan.png'],
    Postiche: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Printer_Specs: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Recluse_Beard: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Scar: ['Eye_Gouge.png', 'Horizontal.png', 'Slash.png', 'Vertical.png', 'Wound.png'],
    Royal_Beard: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Shag: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Sheriff_Whiskers: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Spectacles: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'night.png', 'red.png'],
    Spooky_Mask: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Stern_Brow: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Stubble: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Third_Eye: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Tradesman_Mustache: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Tribal_Markings: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Vigilante_Lens: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    War_Paint: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Wrinkles: ['a.png'],
    Western: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
  },
  Feet: {
    Arcane_Slippers: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Designer_Boots: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Heavy_Greaves: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Plate_Boots: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Sandals: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Shoes: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Tights: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
  },
  Hair: {
    Academic: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Arcane: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Barbarian: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Bard: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'silver.png', 'tan.png', 'white.png'],
    Beggar: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Bowl_Cut: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Brute: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Ceasar: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Casual: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Chignon: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Champion_Coif: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Disheveled: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Elder: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Emotional: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Fab: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Elegant: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Feral: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'tan.png', 'white.png'],
    Greased: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Greasy: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Hip: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Jewelled_Tie: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Horseshoe: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Long_Horseshoe: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Messy: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Medium: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Middle_Part: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Miser: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Mullet: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Noble_Part: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Noble_Ribbon: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Pointed: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Ponytail: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Princely: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Punker: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Regal_Band: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Royal_Curls: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Sellsword: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Sharp_Bun: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Short: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Slacker: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Spiked: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Swept_Back: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Tied_Dreadlocks: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'white.png'],
    Tonsure: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Trainee_Headband: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Tufts: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Unfortunate: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Untamed: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Virtuoso: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Wavy_Tied: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Wimp: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Wing: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Wispy: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Youthful: ['black.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'red.png', 'tan.png', 'white.png'],
  },
  Hat: {
    Adventurer_Cap: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Adept_Hood: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Arcanist_Hood: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Assassin_Mask: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Bandana: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'orange.png', 'red.png', 'tan.png', 'white.png'],
    Bard_Cap: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Beret: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Burqa: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Chainmail_Shroud: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'grey.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Decorated_Helm: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Dwarvish_Helm: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'orange.png', 'red.png', 'tan.png', 'white.png'],
    Fez: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Gardener_Bonnet: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Gladiator_Helm: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'grey.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Hijab: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Gourmand_Hat: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Hunter_Hood: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Imp_Cap: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Infantry_Helm: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'grey.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Knight_Helmet: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'grey.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Keffiyeh: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Jester_Cap: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Lunar_Cap: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Nemes: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Mystic_Hood: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Northern_Crown: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'white.png'],
    Pelt: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Produce_Helm: ['apple.png', 'cabbage.png', 'eggplant.png', 'jackolantern.png', 'watermelon.png'],
    Ram_Knight: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Royal_Cap: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Royal_Turban: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Sorcerer_Cap: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Squire_Helm: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'grey.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Southern_Crown: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Thief_Hood: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Toth_Headress: ['organic.png', 'ornate.png'],
    United_Crowns: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Trickster_Hat: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Turban: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Vigilante_Hat: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Warrior_Crown: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Warrior_Helm: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'grey.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Winged_Helm: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Witch_Hat: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
  },
  Lower: {
    Adept_Robe: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Athletic_Shorts: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Barbarian_Tatters: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Belted_Kilt: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Cassock: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Codpiece: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Cutoffs: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Desert_Loincloth: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Druid_Robe: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Genie_Pants: ['black.png', 'blue.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Grim_Leggings: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Hag_Skirt: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Lowrise: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Magician_Gown: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Martial_Shorts: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Miner_Slacks: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Mystic_Robes: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Necromancer_Cloth: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Overalls: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Pharaoh_Cloth: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Royal_Sash: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Senator_Attire: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Savage_Skirt: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Silk_Shift: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'grey.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Sling: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Sorcerer_Cloth: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Stargazer_Skirt: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Swindler_Robes: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Toga: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Trader_Slacks: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Underclothes: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Trousers: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Waistcloth: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
  },
  Upper: {
    Adept_Tunic: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'tan.png', 'white.png'],
    Adventurer_Coat: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Alchemy_Robe: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'scarlet.png', 'shadow.png', 'tan.png', 'white.png'],
    Arcanist_Sash: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Beggar_Rags: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Brawler_Vest: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Brassiere: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Button_Up: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Captain_Jacket: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'orange.png', 'red.png', 'tan.png', 'white.png'],
    Celebrant_Robes: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Crusader_Tabard: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Chthonic_Chiton: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'slate.png', 'tan.png', 'white.png'],
    Cuirass: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Cultist_Robes: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Dryad_Gown: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Fencing_Frock: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Fools_Tunic: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Hag_Shawl: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Hauberk: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Hero_Tank: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Journeyman_Coat: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'sky.png', 'tan.png', 'white.png'],
    Knight_Mail: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Kobold_Leathers: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Kuanake: [
      'black.png',
      'blue.png',
      'brown.png',
      'gold.png',
      'green.png',
      'ivory.png',
      'night.png',
      'red.png',
      'tan.png',
      'white.png',
    ],
    Necromancer_Robe: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Pharaoh_Caplet: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Peasant_Shirt: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'scarlet.png', 'tan.png', 'white.png'],
    Pharaoh_Chain: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Pirate_Blouse: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Platemail: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Poet_Tuxedo: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Royal_Robe: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Royal_Tunic: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Shadow_Mail: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Silk_Himation: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Society_Frock: ['beige.png', 'black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Sorcerer_Robes: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Squire_Shirt: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Studded_Leathers: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Swamp_Coat: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Swindler_Coat: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Tatters: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Thief_Cowl: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Training_Top: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Traveler_Shirt: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Undershirt: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
    Woodsprite_Cloak: ['black.png', 'blue.png', 'brown.png', 'gold.png', 'green.png', 'ivory.png', 'night.png', 'red.png', 'tan.png', 'white.png'],
  },
}

export default newData
